<?php
$pageTitle = 'Response Headers + Status Codes';

require_once __DIR__ . '/../lib/functions.php';

$codeRaw = $_GET['code'] ?? '200';
$codeRaw = is_string($codeRaw) ? $codeRaw : '200';
$code = (int) $codeRaw;

$allowedCodes = [200, 201, 302, 400, 403, 404, 418];
if (!in_array($code, $allowedCodes, true)) {
    $code = 200;
}

$format = $_GET['format'] ?? 'html';
$format = is_string($format) ? $format : 'html';
$format = $format === 'json' ? 'json' : 'html';

// Status code must be set before the body is sent.
http_response_code($code);

// These are response headers (server -> client).
header('X-Class9-Demo: response-demo');
header('Cache-Control: no-store');

if ($format === 'json') {
    header('Content-Type: application/json; charset=UTF-8');

    $payload = [
        'status' => http_response_code(),
        'ok' => $code >= 200 && $code < 300,
        'message' => 'This response was generated by PHP.',
        'time' => date('c'),
        'headersSetByPhp' => headers_list(),
    ];

    $json = json_encode($payload, JSON_PRETTY_PRINT);
    if ($json === false) {
        $json = '{"error":"json_encode failed"}';
    }

    print $json . "\n";
    exit;
}

require_once __DIR__ . '/../partials/header.php';
?>

<p><a href="../index.php">Home</a></p>

<p>
    This page demonstrates setting a status code with <code>http_response_code()</code> and
    setting response headers with <code>header()</code>.
</p>

<h2>Try It</h2>
<ul>
    <li><a href="response-demo.php">HTML (200)</a></li>
    <li><a href="response-demo.php?code=404">HTML (404)</a></li>
    <li><a href="response-demo.php?code=418">HTML (418)</a></li>
    <li><a href="response-demo.php?format=json">JSON (200)</a></li>
    <li><a href="response-demo.php?code=404&amp;format=json">JSON (404)</a></li>
</ul>

<h2>Current Response</h2>
<dl>
    <dt>Status code</dt>
    <dd><?php print (int) http_response_code(); ?></dd>

    <dt>Format</dt>
    <dd><?php print h($format); ?></dd>
</dl>

<h2>Headers Set by PHP</h2>
<p>
    <code>headers_list()</code> shows the headers that PHP set for this response.
</p>
<pre><?php print h(implode("\n", headers_list())); ?></pre>

<p>
    Open DevTools -> Network and click this request to see the status code and headers.
</p>

<?php
require_once __DIR__ . '/../partials/footer.php';
