<?php
$pageTitle = 'Remote Data + Caching (Filesystem)';

require_once __DIR__ . '/../lib/functions.php';

// Remote CSV source (public dataset). If it is slow or unavailable, the page
// will show an error message, and you can still discuss the caching logic.
$dataUrl = 'https://www.maine.gov/labor/cwri/laus/Population1960_2000.csv';

$cacheDir = __DIR__ . '/../storage/cache';
if (!is_dir($cacheDir)) {
    mkdir($cacheDir, 0777, true);
}

$cacheFile = $cacheDir . '/cached-population-table.html';

$ttlDays = 7;
$ttlSeconds = $ttlDays * 86400;

$refresh = $_GET['refresh'] ?? '';
$refresh = is_string($refresh) ? $refresh : '';
$refresh = $refresh === '1';

$maxRowsRaw = $_GET['max'] ?? '16';
$maxRowsRaw = is_string($maxRowsRaw) ? $maxRowsRaw : '16';
$maxRows = (int) $maxRowsRaw;
if ($maxRows < 1 || $maxRows > 100) {
    $maxRows = 16;
}

$cacheAgeSeconds = is_file($cacheFile) ? (time() - (int) filemtime($cacheFile)) : null;
$cacheFresh = $cacheAgeSeconds !== null && $cacheAgeSeconds <= $ttlSeconds;

$source = '';
$tableHtml = '';
$error = '';

if (!$refresh && $cacheFresh) {
    $cached = file_get_contents($cacheFile);
    if (is_string($cached)) {
        $source = 'cache';
        $tableHtml = $cached;
    } else {
        $error = 'Could not read cache file.';
    }
}

if ($tableHtml === '') {
    $source = 'remote';

    $context = stream_context_create([
        'http' => [
            'timeout' => 8,
            'header' => "User-Agent: CIS333-Class9\r\n",
        ],
    ]);

    $handle = fopen($dataUrl, 'r', false, $context);
    if ($handle === false) {
        $error = 'Could not open remote URL. (Check allow_url_fopen and network access.)';
    } else {
        // Build HTML in a string so we can both display it and cache it.
        ob_start();
        print '<table border="1" cellpadding="6">';
        print '<thead><tr><th>County</th><th>Population (2000)</th></tr></thead>';
        print '<tbody>';

        $rowsPrinted = 0;

        while (($line = fgetcsv($handle)) !== false) {
            // The dataset includes both towns and counties.
            // Column 1 is a label like "County" for county rows.
            if (($line[1] ?? '') !== 'County') {
                continue;
            }

            $countyName = (string) ($line[0] ?? '');
            $population2000 = (string) ($line[6] ?? '');

            print '<tr>';
            print '<td>' . h($countyName) . '</td>';
            print '<td>' . h($population2000) . '</td>';
            print '</tr>';

            $rowsPrinted++;
            if ($rowsPrinted >= $maxRows) {
                break;
            }
        }

        print '</tbody></table>';
        $tableHtml = (string) ob_get_clean();

        fclose($handle);

        // Cache the rendered HTML so we don't have to re-download and re-process
        // the data on every request.
        $bytesWritten = file_put_contents($cacheFile, $tableHtml, LOCK_EX);
        if ($bytesWritten === false) {
            $error = 'Fetched remote data, but failed to write cache file.';
        }

        $cacheAgeSeconds = is_file($cacheFile) ? (time() - (int) filemtime($cacheFile)) : null;
        $cacheFresh = $cacheAgeSeconds !== null && $cacheAgeSeconds <= $ttlSeconds;
    }
}

require_once __DIR__ . '/../partials/header.php';
?>

<p><a href="/">Home</a></p>

<p>
    This page demonstrates a common web-development pattern: download remote data, generate output, then
    cache the result on disk so future requests are fast and reliable.
</p>

<h2>Configuration</h2>
<dl>
    <dt>Remote URL</dt>
    <dd><code><?php print h($dataUrl); ?></code></dd>

    <dt>Cache file</dt>
    <dd><code><?php print h($cacheFile); ?></code></dd>

    <dt>TTL</dt>
    <dd><?php print (int) $ttlDays; ?> days</dd>

    <dt>Max rows</dt>
    <dd><?php print (int) $maxRows; ?></dd>
</dl>

<h2>Cache Status</h2>
<dl>
    <dt>Cache exists</dt>
    <dd><?php print is_file($cacheFile) ? 'yes' : 'no'; ?></dd>

    <dt>Cache age (seconds)</dt>
    <dd><?php print $cacheAgeSeconds === null ? '(n/a)' : (int) $cacheAgeSeconds; ?></dd>

    <dt>Cache fresh</dt>
    <dd><?php print $cacheFresh ? 'yes' : 'no'; ?></dd>

    <dt>Source used</dt>
    <dd><?php print h($source); ?></dd>
</dl>

<h2>Controls</h2>
<ul>
    <li><a href="/remote-cache">Use cache if fresh</a></li>
    <li><a href="/remote-cache?refresh=1">Force refresh (ignore cache)</a></li>
    <li><a href="/remote-cache?<?php print h(http_build_query(['max' => 5])); ?>">Limit to 5 rows</a></li>
</ul>

<?php if ($error !== '') : ?>
    <p><strong><?php print h($error); ?></strong></p>
<?php endif; ?>

<h2>Output</h2>
<?php
// $tableHtml was generated by our script, and it contains only escaped values.
// We print it as HTML intentionally.
print $tableHtml;
?>

<p>
    Open DevTools -> Network and refresh this page. On the first load (or a forced refresh), it may be slower.
    On later loads, it should be much faster when it can read from the cache.
</p>

<?php
require_once __DIR__ . '/../partials/footer.php';
